config/routes.rb
Rails.application.routes.draw do
  # 　管理者側のルーティング
  namespace :admin do
    resources :bookings
    resources :hotels do # Good ^_^
      resources :rooms
    end
    resources :rooms # No Good T_T
    resources :customers, only: [:index, :show, :destroy]
    resources :reviews
    get "customers/unsubscribe"
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about"
    post "homes" => "homes#create"
    post "homes/done" => "homes#done"
    get "sessions/new" => "sessions#new"
    get "customers/mypage" => "customers#mypage"
    get "search" => "searches#search"
    post "bookings/confirm" => "bookings#confirm"
    get "bookings/thanks" => "bookings#thanks"
    post "bookings" => "bookings#create"

    resources :customers
    resources :hotels
    resources :bookings, only: [:create, :new]
    # コメント機能のネスト部分
    resources :hotels do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :rooms do
  resources :bookings
end

  # ゲストログイン
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  extend OrderAsSpecified

  belongs_to :hotel
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  belongs_to :admin

  scope :is_view, -> { where(is_view: true) }

   # ActiveStorageの設定
  has_one_attached :image

  validates :room_name, presence: true
  validates :room_details, presence: true
  validates :price, presence: true
  validates :booking_date, presence: true
  validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'] }

  #ソート機能
  scope :by_booking_date, -> { order(booking_date: :asc) }
  scope :by_price, -> { order(price: :asc) }

  # 検索方法分岐
  def self.looks(search, word, range)
    if search == "perfect_match"
      if range == "部屋名"
        Room.where("room_name LIKE?", "#{word}")
      elsif range == "金額"
        Room.where("price LIKE?", "#{word}")
      else
        Room.where("booking_date LIKE?","#{word}")
      end
    elsif search == "partial_match"
      if range == "部屋名"
        Room.where("room_name LIKE?", "%#{word}%")
      elsif range == "金額"
        Room.where("price LIKE?", "%#{word}%")
      else
        Room.where("booking_date LIKE?","%#{word}%")
      end
    else
      Room.all
    end
  end

 # タグ付けの新規投稿用メソッド
  def save_tags(tags)
    tags.each do |new_tags|
      # selfは明示的に記載していてこの場合だとコントローラーの@postになる
      # tag_relationshipsがthroughしているのでtagsでアソシエーションを指定すると中間テーブルを通過した際に保存される。
      self.tags.find_or_create_by(name: new_tags)
    end
  end

  # タグ付けの更新用メソッド
  def update_tags(latest_tags)
    if self.tags.empty?
      # 既存のタグがなかったら追加だけ行う
      latest_tags.each do |latest_tag|
        self.tags.find_or_create_by(name: latest_tag)
      end
    elsif latest_tags.empty?
      # 更新対象のタグがなかったら既存のタグをすべて削除
      # 既に保存がされていたら既に登録されているタグの内容を削除
      self.tags.each do |tag|
        self.tags.delete(tag)
      end
    else
      # 既存のタグも更新対象のタグもある場合は差分更新
      current_tags = self.tags.pluck(:name)
      #左を起点に引き算をする
      #　　　　　　 b             a b c
      old_tags = current_tags - latest_tags
      #一致したものを取り出す
      # a c       a b c            b
      new_tags = latest_tags - current_tags

      # a  c
      old_tags.each do |old_tag|
        tag = self.tags.find_by(name: old_tag)
        self.tags.delete(tag) if tag.present?
      end


      new_tags.each do |new_tag|
        # b
        self.tags.find_or_create_by(name: new_tag)
        # self.tags << new_tags
      end
    end
  end

  def save_hotel_tags(tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tag_relationships.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      tag_relationships = Tag.find_or_create_by(name:new_name)
      self.tags << tag_relationships
    end
  end


end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
    @tags = @post&.tags&.pluck(:name)&.join(",")
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      tags = params[:room][:tag].split(",").uniq
      @room.save_hotel_tags(tags)
      flash[:notice] = "投稿が完了しました。"
      redirect_to admin_bookings_path
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
    @tags = @room.tags.pluck(:name).join(",")
  end

  def update
    @room = Room.find(params[:id])
    # :roomはroomで投稿されてきた際にパラメーターとして飛ばされ、その中の[:tag_id]を取得して、splitで,区切りにしている
    tags = params[:room][:tag].split(",").uniq
    if @room.save_hotel_tags(tags)
      # @roomをつけることroomモデルの情報を.save_tagsに引き渡してメソッドを走らせることができる
      @room.update_tags(tags)
      redirect_to root_path, success: t("rooms.edit.edit_success")
    else
      render :edit
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path, success: t("rooms.destroy.destroy_success")
  end

private
  def room_params
    params.require(:room).permit(:hotel_id, :room_name, :room_details, :price, :image, :admin_id, :booking_date)
                          .merge(admin_id: current_admin.id)
  end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/views/admin/rooms/edit.html.erb
<div class ='row'>
   <div class="col-sm-10 offset-sm-5 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
<h1>部屋詳細編集画面</h1>

<%= form_with model: @room, url: admin_room_path do |f| %>
  <h4>ホテル名</h4>
  <%= f.collection_select :hotel_id, Hotel.all, :id, :hotel_name, {include_blank: "選択して下さい"}, class: 'form-control' %>

  <h4>予約日</h4>
  <%= f.date_field :booking_date, class: "form-control" %>

  <h4>部屋名</h4>
  <%= f.text_field :room_name, class: "form-control" %>

  <h4>部屋内容</h4>
  <%= f.text_field :room_details, class: "form-control" %>

  <h4>部屋料金</h4>
  <%= f.text_field :price, class: "form-control" %>

  <h4>部屋画像</h4>
  <%= f.file_field :image, accept: "image/*" %>


  <h4>タグ</h4>
  <%= f.text_field :tag, class: "form-control", value: @tags %>



  <%= f.submit '登録', class: "btn btn-success btn-lg btn-block" %>
  <% end %>

   </div>
</div>

app/views/admin/rooms/new.html.erb
<div class="container">
<div class ='row'>
   <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
<h1>部屋詳細登録</h1>

<!--バリデーション-->
<% if @room.errors.any? %>
  <%= @room.errors.count %>件のエラーが発生しました
  <ul>
    <% @room.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @room, url: admin_rooms_path do |f| %>
  <h4>ホテル名</h4>
  <%= f.collection_select :hotel_id, current_admin.hotels, :id, :hotel_name, {include_blank: "選択して下さい"}, class: 'form-control' %>

  <h4>予約日</h4>
  <%= f.date_field :booking_date, class: "form-control" %>

  <h4>部屋名</h4>
  <%= f.text_field :room_name, class: "form-control" %>

  <h4>部屋内容</h4>
  <%= f.text_area :room_details, class: "form-control" %>

  <h4>部屋料金</h4>
  <%= f.text_field :price, class: "form-control" %>

  <h4>部屋画像</h4>
  <%= f.file_field :image, accept: "image/*" %>


  <h4>タグ</h4>
  <%= f.text_field :tag, class: "form-control" %>



  <%= f.submit '登録', class: "btn btn-outline-secondary btn-lg btn-block mt-2" %>
  <% end %>

   </div>
</div>
</div>

app/views/admin/rooms/show.html.erb
<h1>部屋詳細画面</h1>