config/routes.rb
Rails.application.routes.draw do
  # 　管理者側のルーティング
  namespace :admin do
    resources :bookings
    resources :hotels do # Good ^_^
      resources :rooms
    end
    resources :rooms # No Good T_T
    resources :customers, only: [:index, :show, :destroy]
    resources :reviews
    get "customers/unsubscribe"
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about"
    post "homes" => "homes#create"
    post "homes/done" => "homes#done"
    get "sessions/new" => "sessions#new"
    get "customers/mypage" => "customers#mypage"
    get "search" => "searches#search"
    post "bookings/confirm" => "bookings#confirm"
    get "bookings/thanks" => "bookings#thanks"
    post "bookings" => "bookings#create"

    resources :customers
    resources :hotels
    resources :bookings, only: [:create, :new]
    # コメント機能のネスト部分
    resources :hotels do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :rooms do
  resources :bookings
end

  # ゲストログイン
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true

  # ゲストログイン入力項目
  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_CUSTOMER_EMAIL, first_name: "test", last_name: "test", first_name_kana: "テスト", last_name_kana: "テスト") do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit; end

  def unsubscribe; end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:notice] = "ユーザーを退会処理しました。"
    redirect_to admin_customers_path
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1>Admin::Customers#edit</h1>
<p>Find me in app/views/admin/customers/edit.html.erb</p>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
      <h1>会員一覧</h1>

<table class = "table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <!--<th>メールアドレス</th>-->
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td>
          <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.first_name %>
          <%= customer.last_name %></td>
    <% end %>
      <!--<td><%#= customer.email %></td>-->
    </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

app/views/admin/customers/show.html.erb
  <div class="row">
    <div class="col-sm-10 offset-sm-2 col-md-8 offset-md-2 col-lg-10">

<h4><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h4>

<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td><%= @customer.id %></td>
    <td><%= @customer.first_name %><%= @customer.last_name %></td>
    <td><%= @customer.email %></td>
    <td><%= link_to "退会処理", admin_customer_path(@customer.id), method: :delete, class: "btn btn-outline-danger", "data-confirm" => "本当に退会させますか？" %></td>
    </tr>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/admin/customers/unsubscribe.html.erb
<h1>Admin::Customers#unsubscribe</h1>
<p>Find me in app/views/admin/customers/unsubscribe.html.erb</p>