config/routes.rb
Rails.application.routes.draw do
  # 　管理者側のルーティング
  namespace :admin do
    resources :bookings
    resources :hotels do # Good ^_^
      resources :rooms
    end
    resources :rooms # No Good T_T
    resources :customers, only: [:index, :show, :destroy]
    resources :reviews
    get "customers/unsubscribe"
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about"
    post "homes" => "homes#create"
    post "homes/done" => "homes#done"
    get "sessions/new" => "sessions#new"
    get "customers/mypage" => "customers#mypage"
    get "search" => "searches#search"
    post "bookings/confirm" => "bookings#confirm"
    get "bookings/thanks" => "bookings#thanks"
    post "bookings" => "bookings#create"

    resources :customers
    resources :hotels
    resources :bookings, only: [:create, :new]
    # コメント機能のネスト部分
    resources :hotels do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :rooms do
  resources :bookings
end

  # ゲストログイン
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :rooms, dependent: :destroy
  belongs_to :admin

  validates :hotel_name, presence: true
  validates :body, presence: true
  validates :url, presence: true
  validates :telephone_number, presence: true
  validates :address, presence: true

  geocoded_by :address # addressカラムの内容を緯度・経度に変換すること
  after_validation :geocode # バリデーションの実行後に変換処理を実行して、latitudeカラム・longitudeカラムに緯度・経度の値が入力される

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      hotels = Hotel.where("hotel_name LIKE?", "#{word}")
    elsif search == "partial_match"
      hotels = Hotel.where("hotel_name LIKE?", "%#{word}%")
    else
      hotels = Hotel.all
    end
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
     @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      flash[:notice] = '施設名を登録しました。'
      redirect_to admin_hotel_path(@hotel.id)
    else
      render :new
    end
  end

  def index
    @hotels = Hotel.all
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    hotel = Hotel.find(params[:id])
    hotel.update(hotel_params)
    redirect_to admin_hotel_path(hotel.id)
  end

  def destroy
    hotel = Hotel.find(params[:id])
    hotel.destroy
    flash[:notice] = "宿泊施設を削除しました。"
    redirect_to admin_hotels_path
  end

 private

  def hotel_params
  params.require(:hotel).permit(:hotel_name, :body, :url, :telephone_number, :address).merge(admin_id: current_admin.id)
  end
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/views/admin/hotels/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <h1>宿泊施設編集画面</h1>
    <%= form_with model: @hotel, url: admin_hotel_path(@hotel.id), method: :patch do |f| %>

      <div class="form-group pt-2">
      <h4>宿泊施設名</h4>
      <%= f.text_field :hotel_name, class: "form-control" %>
      </div>

      <div class="form-group">
      <h4>部屋詳細</h4>
      <%= f.text_field :body, class: "form-control" %>
      </div>

      <div class="form-group">
      <h4>サイト名</h4>
      <%= f.text_field :url, class: "form-control" %>
      </div>

      <div class="form-group">
      <h4>電話番号</h4>
      <%= f.text_field :telephone_number, class: "form-control" %>
      </div>

      <div class="form-group">
      <h4>住所</h4>
      <%= f.text_field :address, class: "form-control" %>
      </div>

      <%= f.submit "保存", class: "btn btn-outline-secondary mt-2" %>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/hotels/index.html.erb
<div class="container">
  <div class="row">
    <h1>宿泊施設一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>宿泊施設名</th>
      <th>部屋詳細</th>
      <th>サイト名</th>
      <th>電話番号</th>
      <th>住所</th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.hotel_name %></td>
        <td><%= hotel.body %></td>
        <td><%= hotel.url %></td>
        <td><%= hotel.telephone_number %></td>
        <td><%= hotel.address %></td>
        <td><%= link_to "編集", edit_admin_hotel_path(hotel.id), class: "btn btn-outline-secondary" %></td>
        <td><%= link_to "削除", admin_hotel_path(hotel.id), method: :delete, "data-confirm" => "本当に削除しますか？",  class: "btn btn-outline-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

app/views/admin/hotels/new.html.erb
<div class ='row'>
   <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
<h1>宿泊施設登録</h1>

<!--バリデーション-->
<% if @hotel.errors.any? %>
  <%= @hotel.errors.count %>件のエラーが発生しました
  <ul>
    <% @hotel.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @hotel, url: admin_hotels_path do |f| %>
  <div class="form-group">
    <h4>宿泊施設名</h4>
    <%= f.text_field :hotel_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <h4>詳細</h4>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <h4>ホームページ</h4>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <h4>電話番号</h4>
    <%= f.text_field :telephone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <h4>郵便番号</h4>
    <small>(住所検索用)</small>
    <%= text_field_tag :zipcode, nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <h4>住所</h4>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <%= f.submit '登録', class: "btn btn-outline-secondary btn-lg btn-block mt-2" %>
  <% end %>

   </div>
</div>

<!--Javascriptを読み込む処理-->
<%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>

app/views/admin/hotels/show.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-5 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <h2>ホテル詳細</h2>
    <p>宿泊施設名：<span><%= @hotel.hotel_name %></span></p>
    <p>詳細：<span><%= @hotel.body %></span></p>
    <p>ホームページ：<span><%= @hotel.url %></span></p>
    <p>電話番号：<span><%= @hotel.telephone_number %></span></p>
    <p>住所：<span><%= @hotel.address %></span></p>
  </div>
</div>