config/routes.rb
Rails.application.routes.draw do
  # 　管理者側のルーティング
  namespace :admin do
    resources :bookings
    resources :hotels do # Good ^_^
      resources :rooms
    end
    resources :rooms # No Good T_T
    resources :customers, only: [:index, :show, :destroy]
    resources :reviews
    get "customers/unsubscribe"
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about"
    post "homes" => "homes#create"
    post "homes/done" => "homes#done"
    get "sessions/new" => "sessions#new"
    get "customers/mypage" => "customers#mypage"
    get "search" => "searches#search"
    post "bookings/confirm" => "bookings#confirm"
    get "bookings/thanks" => "bookings#thanks"
    post "bookings" => "bookings#create"

    resources :customers
    resources :hotels
    resources :bookings, only: [:create, :new]
    # コメント機能のネスト部分
    resources :hotels do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :rooms do
  resources :bookings
end

  # ゲストログイン
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>cancle matching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c3fd8eb30a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <header class="position-fixed w-100" style="background-color: #fff;">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "IMG_6641.png", alt: "Image", class: 'logo' %>
          <% end %>
          <i class="fa-solid fa-magnifying-glass" style="color:white;"></i>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border-color:white;">
            <span class="navbar-toggler-icon" style="border-color:white;"></span>
          </button>

          <div class ="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class = "navbar-nav ml-auto">
              <% if customer_signed_in? %>
                 <!--<p class="text-light pr-5">ようこそ<%#= current_customer.last_name %>さん</p>-->

                  <li class="nav-item"><%= link_to 'マイページ',customers_mypage_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'About', homes_about_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'ホテル一覧', hotels_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'ログアウト',  destroy_customer_session_path, method: :delete, class: "nav-link" %></li>

              <% elsif admin_signed_in? %>
                  <li class="nav-item"><%= link_to '投稿一覧', admin_bookings_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to '宿泊施設一覧', admin_hotels_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to '会員一覧', admin_customers_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'レビュー一覧', admin_reviews_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to '宿泊施設登録', new_admin_hotel_path, class: "nav-link", data: {"turbolinks" => false} %></li>
                  <li class="nav-item"><%= link_to '部屋登録', new_admin_room_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link" %></li>

              <% else %>
                  <li class="nav-item"><%= link_to "ゲストログイン", customers_guest_sign_in_path, class: "nav-link", method: :post %></li>
                  <li class="nav-item"><%= link_to 'About', homes_about_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to '新規登録',   new_customer_registration_path,class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'ログイン', new_customer_session_path,class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to '宿泊施設側新規登録',  new_admin_registration_path,class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to '宿泊施設側ログイン', new_admin_session_path, class: "nav-link" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
          <%# deivseのフラッシュメッセージを表示 %>
          <% if notice %>
            <div class="container">
              <p class="notice"><%= notice %></p>
            </div>
          <% end %>
          <% if alert %>
            <div class="container">
              <p class="alert"><%= alert %></p>
            </div>
          <% end %>

        <main class="flex-grow-1">
          <%= yield %>
        </main>
      <footer class="footer-wrapper">
        <div class="container d-flex flex-column">
          <%= image_tag "IMG_6641.png", class: 'img-fluid' %>
          <ul class="list-unstyled mb-3">
            <li>会社概要</li>
            <li>利用規約</li>
            <li>プライバシーポリシー</li>
          </ul>
        </div>
        <div class="text-center">
          <small class="text-black-50">
            &copy; 2024 AmiImamura
          </small>
        </div>
      </footer>
      <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>